version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_DATABASE=taskmanager
      - DB_USERNAME=lgomesroc
      - DB_PASSWORD=12345
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "5577azcD@#"
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: lgomesroc
      MYSQL_PASSWORD: 12345
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data: