version: '3.8'

services:
  # Serviço do backend (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - DB_HOST=db
      - DB_DATABASE=taskmanager
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    depends_on:
      - db

  # Serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: taskmanager
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
